# Generated by Django 5.2.7 on 2025-10-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('managementapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out')], max_length=50)),
                ('entity_type', models.CharField(choices=[('booking', 'Booking'), ('user', 'User'), ('custom_user', 'Custom User'), ('system', 'System')], max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by_custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to='authapp.customuser')),
                ('performed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_d8c226_idx'), models.Index(fields=['action'], name='activity_lo_action_b49f28_idx'), models.Index(fields=['entity_type'], name='activity_lo_entity__97ab7c_idx')],
            },
        ),
    ]
