# Generated by Django 5.2.7 on 2025-11-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(blank=True, help_text='Type of menu/food arrangement', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_packs',
            field=models.CharField(blank=True, help_text='Number of packs/guests', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('bartamanda', 'Bartamanda/Rice Feeding'), ('conference', 'Conference'), ('birthday', 'Birthday Party'), ('anniversary', 'Anniversary'), ('corporate', 'Corporate Event'), ('engagement', 'Engagement'), ('bratabandha', 'Bratabandha'), ('reception', 'Reception'), ('seminar', 'Seminar/Workshop'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
