# Generated by Django 5.2.8 on 2025-11-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0003_booking_menu_type_booking_no_of_packs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_full_day',
            field=models.BooleanField(default=False, help_text='If checked, no other bookings allowed on this date'),
        ),
    ]
