# Generated by Django 5.2.8 on 2025-12-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0004_booking_is_full_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'time_slot'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_full_day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_packs',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_pax',
            field=models.CharField(blank=True, help_text='Additional number of pax', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_pax',
            field=models.CharField(blank=True, help_text='Number of pax/guests', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('morning', '6 AM - 3 PM'), ('evening', '3 PM - 9 PM'), ('fullday', 'Full Day')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(blank=True, choices=[('party', 'Party'), ('newari_bhoj', 'Newari Bhoj'), ('jabhu_bhoj', 'Jabhu Bhoj'), ('others', 'Others')], help_text='Type of menu/food arrangement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
