# Generated by Django 5.2.8 on 2025-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0005_alter_booking_options_remove_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('bartamanda', 'Bartamanda'), ('Rice Feeding', 'Rice Feeding'), ('conference', 'Conference'), ('birthday', 'Birthday Party'), ('anniversary', 'Anniversary'), ('corporate', 'Corporate Event'), ('engagement', 'Engagement'), ('bratabandha', 'Bratabandha'), ('reception', 'Reception'), ('seminar', 'Seminar/Workshop'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
