# Generated by Django 5.2.8 on 2025-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0006_alter_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per pax/plate', max_digits=10, null=True),
        ),
    ]
